### ISSUE TITLE
Provide a simplified responder creation user experience

### ISSUE THREAD

**Issue by azasypkin** [secutils-dev/secutils#47]
## Summary
Over time, the number of responder properties that users can configure has grown, making the UI a little confusing, especially for new users of Secutils.dev. In this issue, we need to remove as much friction as possible in getting started with responders while still allowing more advanced users to tune all responder properties. Here are the proposed changes for the `Create responder` UI:

* `Tracking` - We should track responder requests by default with a reasonable default number of retained requests, and can hide the control in the simplified mode.
* `Enabled` - The responder is enabled by default, and we can reserve this switch for advanced editing mode.
* `Subdomain prefix` - If the user's subscription supports subdomain prefixes, we need to auto-generate a random subdomain prefix so that the user doesn't have to think about it.
* `Path` - If subdomain prefixes are supported and the prefix was generated automatically, we can set the path to `/` by default; otherwise, we can auto-generate a random path as well.
* `Path type` - It makes sense to set it to `Prefix` by default only if the path was automatically set to `/`, and hide it in the simplified mode.
* `Method` - This defaults to `ANY`, and it makes sense to hide this selector by default.
* `Status code` - This defaults to `200` and commonly understood property, it's fine to keep it in the simplified mode.
* `Body` - It'd make sense to fill this in by default, e.g., with some HTML.
* `Headers` - Since we want to provide a default HTML body, it'd make sense to prefill this field with `Content-Type: text/html; charset=utf-8` by default, and keep it in the simplified mode.
* `Script` - This field is definitely targeted at advanced users, and we can hide it in the simplified mode.

**Comment by azasypkin** [comment]
The first UX simplification attempt landed in https://github.com/secutils-dev/secutils-webui/commit/3655bc6ba6a669ec471565f6e234ef5c333ad2d2. 

The only field the user is required to fill in now to create a new responder is the responder's name. The rest of the fields will get reasonable defaults that user can tweak if they switch to an `Advanced mode`.

Here's the demo (also includes https://github.com/secutils-dev/secutils/issues/48 and https://github.com/secutils-dev/secutils/issues/36):

https://github.com/secutils-dev/secutils/assets/1713708/0a911536-3c08-4d18-b04b-fae69ac0c208

Hopefully, this change will make `Responders` a bit more usable for you @legrego 🙂

**Comment by legrego** [comment]
This looks great, thanks @azasypkin!
